apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rjyycwudo-python 
  janus-idp.io/tekton: rjyycwudo-python
  backstage.io/kubernetes-id: rjyycwudo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rjyycwudo-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml